site_name: Deltaline Docs
theme:
  name: readthedocs

  favicon: img/favicon.ico
  icon: 
  repo: fontawesome/brands/github
  logo: img/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  primary: black
  accent: pink
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
  markdown_extensions:
  - toc:
      permalink: true
markdown_extensions:
  - attr_list
repo_url: https://github.com/No767/Deltaline-Docs
repo_name: Deltaline Docs
edit_uri: https://github.com/No767/Deltaline-Docs/tree/main/docs
site_url: https://github.com/No767/Deltaline-Docs
analytics:
      gtag: G-9FPH1JDHS8
plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      type: date

nav: 
  - Home: 
    - 'Home': 'index.md'
  - Contributing: 
    - 'Contributing to the Docs': 'Contributing to the docs.md'
    - 'Contributing to Deltaline': 'Contributing to Deltaline.md'
  - How It Works: 
    - 'Django Framework': 'Django Framework.md'
    - 'Structure Layout': 'Structure Layout.md'
  - Issues with the Digital Portfolio:
    - 'Issues with the Digital Portfolio': 'Issues With the Digital Portfolio.md'
  - Plans for Deltaline:
    - 'Plans for Deltaline': 'Plans for Deltaline.md'
  - Terms and Conditions:
      - 'Art Assets': 'Art Assets.md'
      - 'Licensing': 'Licensing.md'
  - About: 
    - 'About Project Deltaline': 'About Project Deltaline.md'
