site_name: Deltaline Docs
theme:
  name: readthedocs
  analytics:
      gtag: G-9FPH1JDHS8
  favicon: img/favicon.ico
  icon: 
  logo: img/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  primary: black
  accent: pink
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
  markdown_extensions:
  - toc:
      permalink: true
markdown_extensions:
  - attr_list
repo_url: https://github.com/No767/Project-Deltaline-Docs
repo_name: Deltaline Docs
edit_uri: https://github.com/No767/Project-Deltaline-Docs/tree/main/docs
repo: fontawesome/brands/github
plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      type: date

nav: 
  - Home: index.md
  - Contributing: 
    - 'Contributing to the Docs': 'Contributing to the docs.md'
    - 'Contributing to Deltaline': 'Contributing to Deltaline.md'
  - How It Works: 
    - 'Structure Layout': 'Structure Layout.md'
  - Issues with the Digital Portfolio:
    - 'Issues with the Digital Portfolio': 'Issues With the Digital Portfolio.md'
  - Terms and Conditions:
      - 'Art Assets': 'Art Assets.md'
  - About: 
    - 'About Project Deltaline': 'About Project Deltaline.md'
