site_name: Deltaline Docs

theme:
  name: readthedocs

plugins:
  - search:
      lang: 
        - en

markdown_extensions:
    - toc:
        permalink: True

repo_url: https://github.com/No767/Deltaline-Docs
repo_name: GitHub
edit_uri: blob/master/docs/
nav: 
  - 'Home': 'index.md'
  - Contributing: 
    - 'Contributing to the Docs': 'Contributing to the docs.md'
    - 'Contributing to Deltaline': 'Contributing to Deltaline.md'
  - How It Works: 
    - 'Django Framework': 'Django Framework.md'
    - 'Structure Layout': 'Structure Layout.md'
  - Issues with the Digital Portfolio:
    - 'Issues with the Digital Portfolio': 'Issues With the Digital Portfolio.md'
  - Plans for Deltaline:
    - 'Plans for Deltaline': 'Plans for Deltaline.md'
  - Terms and Conditions:
      - 'Art Assets': 'Art Assets.md'
      - 'Licensing': 'Licensing.md'
  - About: 
    - 'About Project Deltaline': 'About Project Deltaline.md'
